# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ haskellPackages ? (import <nixpkgs> {}).haskellPackages }:

haskellPackages.cabal.mkDerivation (self: {
  pname = "jumpie";
  version = "0.1.0.0";
  src = "./.";
  isLibrary = false;
  isExecutable = true;
  buildDepends = with haskellPackages; [
    bifunctors clock composition filepath HUnit MonadRandom mtl parsec
    random wrench transformers
  ];
  buildTools = with haskellPackages; [ cabalInstall_1_20_0_6 ghcMod ];
  meta = {
    homepage = "http://github.com/pmiddend/jumpie";
    description = "A simple jump and run game";
    license = self.stdenv.lib.licenses.gpl3;
    platforms = self.ghc.meta.platforms;
  };
})
